### ISSUE TITLE
typo in feedback title

### ISSUE THREAD

**Issue by MahendraBishnoi29** [Germancitoz/mixin-feelings#22]
shouldn't it be incorrect?

<img width="605" alt="Screenshot 2023-02-09 193924" src="https://user-images.githubusercontent.com/74294202/217835851-0e665431-1733-45e1-bda5-463ef2865652.png">

**Comment by Germancitoz** [comment]
Nope, because that option is to correct the wrong answer that the IA provides you. You have to select the right option to improve the IA precision
